name: mafia_gg_bot_dev
channels:
  - defaults
  - conda-forge
dependencies:
  - python==3.7.9
  - pip==20.3.1
  - pip:
    - --extra-index-url=https://pypi.python.org/simple
    - --extra-index-url=https://pypi.anaconda.org/anaconda/simple
    - pytest==6.1.2
